name: publish
on:
  push:
  workflow_dispatch:
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/bharaths44/astro-server:latest
          docker push ghcr.io/bharaths44/astro-server:latest